apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: replite
  name: mongodb
spec:
  replicas: 1
  selector:
     matchLabels:
       app: mongodb
  template:
     metadata:
       labels:
          app: mongodb
     spec:
       containers:
          - name: mongodb
            image: mongo
            ports:
               - containerPort: 27017
            env:
               - name: MONGO_INITDB_ROOT_USERNAME
                 valueFrom:
                    secretKeyRef:
                       name: mongo-auth
                       key: username
               - name: MONGO_INITDB_ROOT_PASSWORD
                 valueFrom:
                    secretKeyRef:
                       name: mongo-auth
                       key: password
            volumeMounts:
               - name: mongo-data
                 mountPath: /data/db
  volumeClaimTemplates:
      - metadata:
           name: mongo-data
        spec:
           storageClassName: fast
           accessModes: [ "ReadWriteOnce" ]
           resources:
              requests: 
                  storage: 10Gi
