apiVersion: apps/v1
kind: StatefulSet
metadata:
   namespace: replite
   name: mongo
spec:
   selector:
      matchLabels:
        environment: dev
   serviceName: "mongo"
   replicas: 3
   template:
     metadata:
        namespace: replite
        labels:
          environment: dev
     spec:
        terminationGracePeriodSeconds: 10
        containers:
        - name: mongo
          image: mongo:3.4.4
          command:
          - mongod
          - "--replSet"
          - rs0
          - "--smallfiles"
          - "--noprealloc"
          ports:
          - containerPort: 27017
          volumeMounts:
          - name: mongo-data
            mountPath: /data/db
   volumeClaimTemplates:
   - metadata:
         name: mongo-data    
     spec:
        storageClassName: "fast" 
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
             storage: 10Gi   
