apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: prometheus-data
   namespace: replite
spec:
   storageClassName: fast
   accessModes:
      - ReadWriteOnce
   resources:
      requests:
         storage: 10Gi
